### ISSUE TITLE
Video mode issue

### ISSUE THREAD

**Issue by hamza-faroooq** [WrathChaos/MediaPickerLib#11]
Hello there,
I am not able to see any of my image and video in simulator or physical device

I write this piece of code

           val intent = Intent(this, Gallery::class.java)
            intent.putExtra("title", "Select Video")
            intent.putExtra("mode", 1)
            intent.putExtra("maxSelection", 1)
            startActivityForResult(intent, 123)

Any Help?

**Comment by kuraydev** [comment]
Hello @hamza-faroooq,
Can you provide with me a reproducible, minimal example?

**Comment by hamza-faroooq** [comment]
just that piece of code nothing else,

also the physical Device name is Honor 8X having Android Version 10

**Comment by kuraydev** [comment]
You need to complete the whole implementation like the [example section](https://github.com/WrathChaos/MediaPickerLib#full-working-example)

Have you checked the working example? 
https://github.com/WrathChaos/MediaPickerLib/tree/master/app

**Comment by hamza-faroooq** [comment]
Sorry for this but i have migrated to another source library (https://github.com/alhazmy13/MediaPicker). that library also causing problem on android 10 but i solved that issue from the issues section (https://github.com/alhazmy13/MediaPicker/issues/107).
