### ISSUE TITLE
Hide tabbar when only images or videos are selected

### ISSUE THREAD

**Issue by msuhl** [WrathChaos/MediaPickerLib#2]
Hi
Thx for a great picker :-)

I need to hide the tabbar when mode 2 or 3 is selected.

I looked into the library code and added tabbar visibility as an extra. It could also be done as a standard, when choosing mode 2 or 3, but I wasn't sure if it should be default?

Should I make a pull request or would you rather that I did not :-)

Regards
Msuhl

**Comment by kuraydev** [comment]
Hello Msuhl,
I'm glad to hear that you like the library :) 
Please make a pull request, PR is always welcome :) Maybe I will not make it by default but it could be an optional feature :) 
After your PR, I will make a new version ASAP.
Thank you so much for contribution :)
Have fun!

**Comment by msuhl** [comment]
Hi again :-)

I get a "403 - not unauthorized" when trying to push my branch?
Could it be a read/write permission issue or am I doing something wrong?

Regards
Msuhl

**Comment by kuraydev** [comment]
Hello @msuhl 
Here is the reason for that : 

> "Those instructions would work if you were a contributor to that project, but you're not. So you need to fork first. Read Fork a Repo. Clone your fork, make the branch there, push and then submit the pull request.
> 
> The your repository vs. their repository isn't really spelled out, but if you look start with your article and click the link for creating a branch you end up at Creating and deleting branches within your repository. Emphasis mine.
> 
> There's a bit more about the two different collaboration models (Fork & Pull vs. Shared Repository) in Using Pull Requests." 

Source : [StackOverFlow](https://stackoverflow.com/questions/29044551/http-403-on-github-pull-request
)
Please try it, if it still does not work please write again and we can create a solution for that :)

**Comment by msuhl** [comment]
Thx for your help - always nice to learn new things :-)
I have created a pull request

Regards 
Msuhl

**Comment by kuraydev** [comment]
Going to release a new version ASAP, thank you again :)
