### ISSUE TITLE
 Caused by: android.view.InflateException: Binary XML file line #34: Could not inflate Behavior subclass android.support.design.widget.

### ISSUE THREAD

**Issue by Davidbr17** [WrathChaos/MediaPickerLib#7]
when i try to start activity , this issue appears

java.lang.RuntimeException: Unable to start activity ComponentInfo{com.ideasreward.link.paymho/com.coursion.freakycoder.mediapicker.galleries.Gallery}: android.view.InflateException: Binary XML file line #34: Could not inflate Behavior subclass android.support.design.widget.Paymho

**Comment by kuraydev** [comment]
Hello @Davidbr17,
Can you share a little project with me to reproduce this issue, therefore I can help you.
