### ISSUE TITLE
Crash due to version of Glide

### ISSUE THREAD

**Issue by hetsgandhi** [WrathChaos/MediaPickerLib#8]
I am using the Glide version 4.9.0 and library uses 4.7.1, due to which app crashes.
Can please the version be upgraded?

Thanks in advance.

**Comment by kuraydev** [comment]
Hello @hetsgandhi,
I'm going to update the gradle ASAP. I will keep you informed.

**Comment by kuraydev** [comment]
Hi again @hetsgandhi,
I've done that. Also migrated to AndroidX and upgraded the kotlin version. Can you please try the new release ?

### [Release: 0.2.0 ](https://github.com/WrathChaos/MediaPickerLib/releases/tag/0.2.0)
